### PR TITLE
T258. Workflow for Work Items

### PR DESCRIPTION
**Pull request by meyginix**
https://trello.com/c/44DEQMlX/258-t258-workflow-for-work-items

### CODE REVIEW

**Comment by RevelsGit** [comment]
Broken work items list

**Comment by RevelsGit** [comment]
When you complete and then undo action there appears to be 2 of the same work items in "my current list".

**Comment by RevelsGit** [comment]
When you complete and then undo root cause analysis it is not dissapears from "my completed list" but instead creates new one in "my current list".

**Comment by RevelsGit** [comment]
Same for update of standards

**Comment by RevelsGit** [comment]
When you update action's "completed by" work item doesn't update

**Comment by RevelsGit** [comment]
same for NCs/Risks

**Comment by meyginix** [comment]
> When you complete and then undo action there appears to be 2 of the same work item in "my current list".
Could not reproduce it.

> When you complete and then undo root cause analysis it does not dissapear from "my completed list" but instead creates new one in "my current list".
> Same for update of standards
This is a correct behaviour.

> When you update action's "completed by" work item doesn't updates
> same for NCs/Risks
I'm not sure if work item needs to be updated in this situation. 
@Praxie, does work item need to updated when document's completedBy changes?

**Pull request merged**
